[package]
name = "http_post"
version = "0.1.0"
authors = ["JP26446"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.10"